FROM debian:latest

ARG BUILDPLATFORM
ARG TARGETPLATFORM
ARG GO_VERSION

# Set environment variables.
ENV GOLANG_VERSION ${GO_VERSION}
ENV TARGET_PLATFORM ${TARGETPLATFORM}
ENV PATH /usr/local/go/bin:$PATH

# Install dependencies.
RUN apt-get update -yq && apt-get upgrade -yq && \
    apt-get install -y bzr git git-core curl && \
    apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy checksum for use in validation.
COPY "checksums/${TARGET_PLATFORM}/go${GOLANG_VERSION}.sha256" /tmp/

# Needed for string substitution
SHELL ["/bin/bash", "-c"]

# Download SDK and validate.
RUN curl -L "https://go.dev/dl/go$GOLANG_VERSION.${TARGET_PLATFORM/\//-}.tar.gz" -o /tmp/go.tar.gz && \
    echo "$(cat /tmp/go${GOLANG_VERSION}.sha256)  /tmp/go.tar.gz" | sha256sum -c - && \
    tar -C /usr/local -xzf /tmp/go.tar.gz && \
    rm /tmp/go.tar.gz /tmp/go${GOLANG_VERSION}.sha256 && \
    mkdir -p /go/src /go/bin && chmod -R 777 /go && \
    uname -m

# Set GOPATH and PATH.
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
ENV TARGET_PLATFORM ""
ENV SHELL /bin/bash

ENTRYPOINT ["bash"]
